version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: development
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /
    target-branch: development
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    target-branch: development
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    target-branch: development
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /apps/web
    target-branch: development
    schedule:
      interval: weekly
