[package]
name = "deepref-server"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
deepref-http-api.workspace = true
deepref-config.workspace = true
deepref-telemetry.workspace = true
deepref-worker = { path = "../../services/worker" }
anyhow.workspace = true
tokio.workspace = true
