[package]
name = "deepref-documents"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
bytes.workspace = true
deepref-application.workspace = true
deepref-domain.workspace = true
object_store.workspace = true
pdfium-render.workspace = true
reqwest.workspace = true
sha2.workspace = true
futures.workspace = true
tokio.workspace = true
thiserror.workspace = true
uuid.workspace = true
url.workspace = true

[dev-dependencies]

[package.metadata.deepref]
layer = "adapter"
