{{- $root := . -}}
{{- range $component, $name := .Values.serviceAccounts }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ include "deepref.namespace" $root }}
  labels:
    {{- include "deepref.labels" $root | nindent 4 }}
    app.kubernetes.io/component: {{ $component | kebabcase }}
automountServiceAccountToken: false
{{- end }}
