[package]
name = "deepref-telemetry"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
deepref-config.workspace = true
thiserror.workspace = true
tracing.workspace = true
opentelemetry.workspace = true
opentelemetry-otlp.workspace = true
opentelemetry_sdk.workspace = true
tracing-opentelemetry.workspace = true
tracing-subscriber.workspace = true

[package.metadata.deepref]
layer = "adapter"
