[package]
name = "deepref-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
deepref-application.workspace = true
deepref-graph.workspace = true
chrono.workspace = true
deepref-domain.workspace = true
serde_json.workspace = true
serde.workspace = true
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
